version: "3.7"

services:
  pg_db:
    image: postgres:14
    restart: on-failure
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - todo_app_pg:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432

volumes:
  todo_app_pg:

